// <auto-generated />
namespace SOSamples_SimpleMembership.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCol_UserProfile_Email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCol_UserProfile_Email));
        
        string IMigrationMetadata.Id
        {
            get { return "201305141633574_AddCol_UserProfile_Email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
